version: '3.8'

services:
  mcp-jira-admin:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${MCP_PORT:-6000}:6000"
    environment:
      - JIRA_URL=${JIRA_URL}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - ORG_ID=${ORG_ID}
      - ADMIN_API_KEY=${ADMIN_API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge